#include "stm32f10x.h"

void Delay(int time)
{
	volatile int i,j;
	for (i=0;i<time*1;i++)
		j++;
}

int main(void)
{
	//RCC -> APB1ENR |= RCC_APB1ENR_TIM2EN;
	//RCC -> APB1ENR |= RCC_APB1ENR_TIM3EN;
	RCC -> APB2ENR |= RCC_APB2ENR_AFIOEN;
	RCC -> APB2ENR |= RCC_APB2ENR_IOPAEN;
	RCC -> APB2ENR |= RCC_APB2ENR_IOPCEN;
	//RCC -> AHBENR |= RCC_AHBENR_DMA1EN;

	//For PWM
	GPIOA -> CRL = 0xBB334333;
	GPIOA -> CRH = 0x000334B3;
	GPIOB -> CRL = 0x333000BB;
	GPIOB -> CRH = 0xBB8833BB;
	GPIOC -> CRH = 0x33300000;

  while (1)
    {
		GPIOA -> BSRR |= GPIO_BSRR_BR0;
		GPIOA -> BSRR |= GPIO_BSRR_BR1;
		GPIOA -> BSRR |= GPIO_BSRR_BR2;
		GPIOC -> BSRR |= GPIO_BSRR_BS15;

		Delay(2000);

		GPIOA -> BSRR |= GPIO_BSRR_BR0;
		GPIOA -> BSRR |= GPIO_BSRR_BS1;
		GPIOA -> BSRR |= GPIO_BSRR_BR2;
		GPIOC -> BSRR |= GPIO_BSRR_BR15;

		Delay(2000);

		GPIOA -> BSRR |= GPIO_BSRR_BR0;
		GPIOA -> BSRR |= GPIO_BSRR_BR1;
		GPIOA -> BSRR |= GPIO_BSRR_BS2;
		GPIOC -> BSRR |= GPIO_BSRR_BR15;

		Delay(2000);

		GPIOA -> BSRR |= GPIO_BSRR_BS0;
		GPIOA -> BSRR |= GPIO_BSRR_BR1;
		GPIOA -> BSRR |= GPIO_BSRR_BR2;
		GPIOC -> BSRR |= GPIO_BSRR_BR15;

		Delay(2000);
    }
}

















